### ISSUE TITLE
Variable naming in to_bdd()

### ISSUE THREAD

**Issue by ericskim** [mvcisback/py-aiger-analysis#27]
@mvcisback 

Renamer only accepts integers in the line below. 
`input_refs_to_var = {ref: renamer(i) for i, ref in enumerate(circ.inputs)}`

Ideally, calling the line below or a similar variant would yield a bdd with variable names that are identical to the names in aiger circuit.
`to_bdd(aagcircuit, renamer = lambda x: str(x))`

Otherwise, we need to get the desired outcome above we need to rename with the dd interface after calling to_bdd.

**Comment by mvcisback** [comment]
@ericskim 

renamer now has the following signature:
```python
def renamer(idx: int, ref: str) -> str:
    pass
```

So to get the names in the aiger circuit, you can use:
```to_bdd(aagcircuit, renamer = lambda x: str(x[0]))```

I still pass in the index in case you want to use the index in your renaming.
